import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signOut, useSession } from "next-auth/react";

import { trpc } from "@/utils/trpc";
import Layout from "@/components/layout/Layout";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="radius flex flex-col items-center gap-2 border p-4">
          <h1 className="text-lg">Home - Not protected</h1>
          <p>
            {session ? "You are authenticated" : "You are not authenticated"}
          </p>
          {session && (
            <div className="flex flex-row gap-2">
              <Link href={"/dashboard"} className="rounded border py-1 px-4">
                Dashboard
              </Link>
              <button
                onClick={() => signOut()}
                className="rounded border py-1 px-4"
              >
                Logout
              </button>
            </div>
          )}

          {!session && (
            <div className="flex flex-row gap-2">
              <Link href={"/login"} className="rounded border py-1 px-4">
                Login
              </Link>
              <Link href={"/register"} className="rounded border py-1 px-4">
                Register
              </Link>
            </div>
          )}
          <p>{hello.data ? hello.data.greeting : "Loading tRPC query..."}</p>
        </div>
      </Layout>
    </>
  );
};

export default Home;
