import type { IRegister } from "@validationauth";
import type { GetServerSideProps, NextPage } from "next";
import { getServerAuthSession } from "@server/common/get-server-auth-session";
import Head from "next/head";
import { useRouter } from "next/router";
import { useForm, type SubmitHandler } from "react-hook-form";
import { useState } from "react";

import { trpc } from "@utils/trpc";

const Register: NextPage = () => {
  const router = useRouter();
  const [errorMessage, setErrorMessage] = useState<string | undefined>();
  const mutation = trpc.auth.register.useMutation({
    onError: (e) => setErrorMessage(e.message),
    onSuccess: () => router.push("/login"),
  });

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IRegister>();

  const onSubmit: SubmitHandler<IRegister> = async (data) => {
    await mutation.mutateAsync(data);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="align-center flex min-h-screen flex-col items-center justify-center gap-1">
        {errorMessage ? (
          <p className="text-center text-red-600">{errorMessage}</p>
        ) : null}
        <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-2">
          <label>Username</label>
          <input
            className="rounded border py-1 px-4"
            type="username"
            {...register("username", { required: true })}
          />
          {errors.username && <span>This field is required</span>}
          <label>Email</label>
          <input
            className="rounded border py-1 px-4"
            type="text"
            {...register("email", { required: true })}
          />
          {errors.email && <span>This field is required</span>}
          <label>Password</label>
          <input
            className="rounded border py-1 px-4"
            type="password"
            {...register("password", { required: true })}
          />
          {errors.password && <span>This field is required</span>}

          <input type="submit" className="rounded border py-1 px-4" />
        </form>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });

  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default Register;
