import type { IRegister } from "@validationauth";
import type { GetServerSideProps, NextPage } from "next";
import { getServerAuthSession } from "@server/common/get-server-auth-session";
import Head from "next/head";
import { useRouter } from "next/router";
import { useForm, type SubmitHandler } from "react-hook-form";

import { trpc } from "@utils/trpc";

const Register: NextPage = () => {
  const router = useRouter();
  const mutation = trpc.auth.register.useMutation();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IRegister>();

  const onSubmit: SubmitHandler<IRegister> = async (data) => {
    const result = await mutation.mutateAsync(data);

    if (result.status === 201) {
      router.push("/login");
    }
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="align-center flex min-h-screen flex-col items-center justify-center gap-1">
        <form onSubmit={handleSubmit(onSubmit)}>
          <input
            className="rounded border py-1 px-4"
            type="username"
            {...register("username", { required: true })}
          />
          {errors.username && <span>This field is required</span>}
          <input type="text" {...register("email", { required: true })} />
          {errors.email && <span>This field is required</span>}
          <input
            className="rounded border py-1 px-4"
            type="password"
            {...register("password", { required: true })}
          />
          {errors.password && <span>This field is required</span>}

          <input type="submit" className="rounded border py-1 px-4" />
        </form>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });

  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default Register;
